apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-buildkit-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-nfs
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/buildkit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-cache
  namespace: orbit
spec:
  accessModes: [ReadWriteMany]
  storageClassName: orbit-nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: orbit-buildkit-pv
