apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-secrets
  namespace: orbit-mongo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: mongo-secrets
  data:
    - secretKey: root_username
      remoteRef:
        key: MONGO_ROOT_USERNAME
    - secretKey: root_password
      remoteRef:
        key: MONGO_ROOT_PASSWORD
