# infrastructure/k8s/plugins-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plugins-service
  namespace: orbit
spec:
  selector:
    app: plugins-service
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
    - name: http
      port: 8080
      targetPort: 8080
