# infrastructure/k8s/orbit-docs/http-route.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: orbit-docs
  namespace: orbit
  annotations:
    external-dns.alpha.kubernetes.io/hostname: docs.orbit.hoytlabs.app
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway
  hostnames:
    - docs.orbit.hoytlabs.app
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: orbit-docs
          port: 3002
