apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-dynamic-config
  namespace: orbit-temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: server
data:
  development-sql.yaml: |
    # Temporal Dynamic Configuration
    # https://docs.temporal.io/references/dynamic-configuration

    system.forceSearchAttributesCacheRefreshOnRead:
      - value: true
        constraints: {}

    limit.maxIDLength:
      - value: 255
        constraints: {}

    history.defaultActivityRetryPolicy:
      - value:
          InitialIntervalInSeconds: 1
          MaximumIntervalCoefficient: 100.0
          BackoffCoefficient: 2.0
          MaximumAttempts: 0
        constraints: {}
