apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-secrets
  namespace: orbit-temporal
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: temporal-secrets
  data:
    - secretKey: postgres_password
      remoteRef:
        key: TEMPORAL_POSTGRES_PASSWORD
    - secretKey: postgres_user
      remoteRef:
        key: TEMPORAL_POSTGRES_USER
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orbit-internal-secrets
  namespace: orbit-temporal
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: orbit-internal-secrets
  data:
    - secretKey: api_key
      remoteRef:
        key: ORBIT_INTERNAL_API_KEY
