apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: temporal-ui-route
  namespace: orbit-temporal
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "temporal.orbit.hoytlabs.app"
spec:
  parentRefs:
    - name: gateway-external
      namespace: gateway
  hostnames:
    - "temporal.orbit.hoytlabs.app"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: temporal-ui
          port: 80
          weight: 1
