apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repository-service-secrets
  namespace: orbit-repository-service
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-secret-store
  target:
    name: repository-service-secrets
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: JWT_SECRET
