apiVersion: v1
kind: ServiceAccount
metadata:
  name: repository-service
  namespace: orbit-repository-service
  labels:
    app.kubernetes.io/name: repository-service
    app.kubernetes.io/component: backend
