apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orbit-redis

resources:
  - namespace.yaml
  - externalsecret.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/part-of: orbit
  app.kubernetes.io/managed-by: argocd

images:
  - name: redis
    newTag: "7-alpine"
