# infrastructure/k8s/repository-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: repository-service
  namespace: orbit
spec:
  selector:
    app: repository-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 8081
      targetPort: 8081
