# infrastructure/k8s/postgresql/pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orbit-postgresql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orbit-nfs
  nfs:
    server: 192.168.86.44
    path: /mnt/tank/appdata/orbit/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: orbit
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: orbit-nfs
  resources:
    requests:
      storage: 10Gi
  volumeName: orbit-postgresql-pv
