apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dynamicconfig-configmap.yaml
  - service.yaml
  - deployment.yaml
  - ui-service.yaml
  - ui-deployment.yaml
  - ui-http-route.yaml
